### PR TITLE
chore:  Make Kaltura plugin work with Hib5

### PR DESCRIPTION
**Pull request by cbeach47**
This is to support the oEQ Spring 5 / Hib 5 upgrade effort - https://github.com/openequella/openEQUELLA/pull/2344

### CODE REVIEW

**Comment by cbeach47** [comment]
There's a couple different ways to handle this PR since this repo has been fairly quiet. 

I think the simplest is to tag the current head of the `master` branch as `2020.1.X`, and then merge this directly onto `master`.  

Open to other ideas.

**Comment by edalex-ian** [comment]
I think first we need to maintain the HEAD of `master` as always working with the latest _released_ version of oEQ. That way being able to build the plugin for the current version is as simple as cloning and building.

So for this PR we wouldn't want to merge it to `master` until about the same time the Hibernate upgrade is merged to `master` of the oEQ repo.

Into the future, perhaps we'll need a `pre-2020.2` branch - which we could create now - and if there's further breaking changes in the future then we'd simply add another similar branch.

But to the here and now of this PR... A few things jump to mind:

1. We have no simple CI (or any tests) for this repo to validate the PR nicely;
2. If agreement was that this PR is good to go - we kind of have nowhere to put it; and
3. I guess we need to modify the oEQ repo's CodeBuild to maybe build this version of the source (which then ideally means we need somewhere to merge this PR) as a means of basic validation.

I was pondering a `develop`, however this would then be out of sync with the oEQ `develop`.

We've got a bit of chicken and egg going on with this one.

**Comment by edalex-ian** [comment]
Ah! Also, did you undertake (or plan to) do some manual testing on this. (Especially seeing the lack of CI and/or automated tests.)

**Comment by cbeach47** [comment]
I did a minor smoke test without a Kaltura account, and I'm tracking down a Kaltura trial account for a better test.

I like the idea of a `develop` branch, so the chicken'n'egg won't be as severe.

Since these kinds of cross-repo synchronized efforts are rare, are you (or I) able to change the CodeBuild logic for just that oEQ PR to point to this PR?

**Comment by edalex-ian** [comment]
> Since these kinds of cross-repo synchronized efforts are rare, are you (or I) able to change the CodeBuild logic for just that oEQ PR to point to this PR?

Ahhh, to my surprise it looks like we easily can. In `buildspec.yml` on your Hibernate branch just change this line:

https://github.com/openequella/openEQUELLA/blob/develop/buildspec.yml#L5

(Note, it still needs to be a branch within this repo - so we can't point to a fork.)

**Comment by edalex-ian** [comment]
> I'm tracking down a Kaltura trial account for a better test

BTW, in case it helps. There is the OSS version of Kaltura at https://www.kaltura.org/

**Comment by cbeach47** [comment]
@edalex-ian  I created a component branch with the same name as the openEQUELLA branch for this effort, and I'm going to merge this PR now so I can point the CodeBuild logic at the newly created component branch for CI testing on the main repo.

We still need to align on the final branches, but I think that's somewhat separate from these testing efforts.

**Pull request merged**
